table Songs
	lineageTag: 3600787b-bd98-4587-a704-f38a4e32d1fd

	measure 'Average Instrumentalness' =
			
			AVERAGE(Songs[Instrumentalness])
		lineageTag: 9a466213-1a3c-4dae-b54f-e75b77782d43

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Popularity' =
			
			AVERAGE('Songs'[Popularity])
		lineageTag: 9a72c3da-0583-48fd-8591-32b9e7617548

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Duration (Minutes)' =
			
			AVERAGE('Songs'[Duration(Min)])
		formatString: 0
		lineageTag: 7d8ebfa8-1ef3-4695-a8d8-78e7c532857c

	measure 'Total Artists' =
			
			DISTINCTCOUNT('Songs'[Artist])
		formatString: 0
		lineageTag: 0fc72b06-bec4-4e8f-aa90-f215d58291c7

	measure 'Total Songs' =
			
			DISTINCTCOUNT('Songs'[Track_ID])
		formatString: 0
		lineageTag: 7b4fe37e-c717-4f41-8e4d-8a62d76315cd

	column Track_ID
		dataType: int64
		formatString: 0
		lineageTag: b16b7cfd-e37f-423b-88bd-108958101f80
		summarizeBy: none
		sourceColumn: Track_ID

		annotation SummarizationSetBy = Automatic

	column Artist
		dataType: string
		lineageTag: 6ab1c789-7034-4065-89eb-52e1e174a108
		summarizeBy: none
		sourceColumn: Artist

		annotation SummarizationSetBy = Automatic

	column Song
		dataType: string
		lineageTag: e12d2586-5e7c-43c6-bbd6-92c1aee688c8
		summarizeBy: none
		sourceColumn: Song

		annotation SummarizationSetBy = Automatic

	column Explicit
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 120ef801-d2e8-4b5e-b16a-be4e07a305ea
		summarizeBy: none
		sourceColumn: Explicit

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: b2d3de30-98bc-4b75-97b1-ba9c391cdc44
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Popularity
		dataType: int64
		formatString: 0
		lineageTag: 52bb0230-29c4-4d11-a6a1-4494fb5dd320
		summarizeBy: none
		sourceColumn: Popularity

		annotation SummarizationSetBy = Automatic

	column Danceability
		dataType: double
		lineageTag: 30f2d867-da33-4c0a-93b0-36b25a4d7290
		summarizeBy: none
		sourceColumn: Danceability

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Energy
		dataType: double
		lineageTag: bad1466f-395b-42d7-8a17-5e4ef88d5cff
		summarizeBy: none
		sourceColumn: Energy

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Key
		dataType: int64
		formatString: 0
		lineageTag: 71291fb3-d850-4458-8e5e-56ee3c8af592
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Loudness
		dataType: double
		lineageTag: 1f193caa-76c5-4fd7-a374-778269fbe315
		summarizeBy: none
		sourceColumn: Loudness

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Mode
		dataType: int64
		formatString: 0
		lineageTag: 46537ac4-4be7-4d0b-b311-1db7044da91a
		summarizeBy: none
		sourceColumn: Mode

		annotation SummarizationSetBy = Automatic

	column Speechiness
		dataType: double
		lineageTag: 2a2b30c1-e331-4787-a5bd-2b9a28f1bf75
		summarizeBy: none
		sourceColumn: Speechiness

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Acousticness
		dataType: double
		lineageTag: 114e4d98-42b6-40f5-ab81-6be706025af9
		summarizeBy: none
		sourceColumn: Acousticness

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Instrumentalness
		dataType: double
		lineageTag: df572bc7-b004-4e70-acfe-722dfe918555
		summarizeBy: none
		sourceColumn: Instrumentalness

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Liveness
		dataType: double
		lineageTag: c84d5c68-4cbf-4f98-bddc-82ab8c9bfc6d
		summarizeBy: none
		sourceColumn: Liveness

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Valence
		dataType: double
		lineageTag: 4c1e1bc6-b9a6-47a3-bb1a-d3a0d4b35800
		summarizeBy: none
		sourceColumn: Valence

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tempo
		dataType: double
		lineageTag: 0120d10f-bd9b-4746-bc76-26921bfd42ab
		summarizeBy: none
		sourceColumn: Tempo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Genre
		dataType: string
		lineageTag: 5bd8c30b-09e8-4ec0-bdf8-58191bcfe366
		summarizeBy: none
		sourceColumn: Genre

		annotation SummarizationSetBy = Automatic

	column 'Key _Name'
		dataType: string
		lineageTag: bf8fe39e-ba15-4c71-b385-377a4bc9fe29
		summarizeBy: none
		sourceColumn: Key _Name

		annotation SummarizationSetBy = Automatic

	column Duration(Min)
		dataType: string
		lineageTag: 06094ca1-3bfc-4a66-b1e3-c71718d65237
		summarizeBy: none
		sourceColumn: Duration(Min)

		annotation SummarizationSetBy = Automatic

	partition Songs = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\ASUS\OneDrive\Desktop\Power BI\Datasets\Spotify dataset.xlsx"), null, true),
				    songs_normalize_Sheet = Source{[Item="songs_normalize",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(songs_normalize_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"artist", type any}, {"song", type text}, {"duration_ms", Int64.Type}, {"explicit", type logical}, {"year", Int64.Type}, {"popularity", Int64.Type}, {"danceability", type number}, {"energy", type number}, {"key", Int64.Type}, {"loudness", type number}, {"mode", Int64.Type}, {"speechiness", type number}, {"acousticness", type number}, {"instrumentalness", type number}, {"liveness", type number}, {"valence", type number}, {"tempo", type number}, {"genre", type text}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "artist", "song", "duration_ms", "explicit", "year", "popularity", "danceability", "energy", "key", "loudness", "mode", "speechiness", "acousticness", "instrumentalness", "liveness", "valence", "tempo", "genre"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "Track_ID"}, {"instrumentalness", "Instrumentalness"}, {"liveness", "Liveness"}, {"valence", "Valence"}, {"tempo", "Tempo"}, {"genre", "Genre"}, {"year", "Year"}, {"explicit", "Explicit"}, {"acousticness", "Acousticness"}, {"speechiness", "Speechiness"}, {"mode", "Mode"}, {"loudness", "Loudness"}, {"key", "Key"}, {"energy", "Energy"}, {"danceability", "Danceability"}, {"popularity", "Popularity"}, {"duration_ms", "Duration_ms"}, {"song", "Song"}, {"artist", "Artist"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Duration", each Number.Round([Duration_ms] / 60000, 2)),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom",{{"Duration", "Duration(Min)"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns1",{"Duration_ms"}),
				    #"Added Custom1" = Table.AddColumn(#"Removed Columns", "Key _Name", each if [Key] = null or [Key] < 0 or [Key] > 11 then "Unknown"
				else {"C", "C#/Db", "D", "D#/Eb", "E", "F", "F#/Gb", "G", "G#/Ab", "A", "A#/Bb", "B"}{[Key]}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Added Custom1",{"Track_ID", "Artist", "Song", "Explicit", "Year", "Popularity", "Danceability", "Energy", "Mode", "Key", "Key _Name", "Loudness", "Speechiness", "Acousticness", "Instrumentalness", "Liveness", "Valence", "Tempo", "Genre", "Duration(Min)"})
				in
				    #"Reordered Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

